export const ADD_TODO = "ADD_TODO";
export const SET_TODOS = "SET_TODOS";
export const START_LOADING_TODOS = "START_LOADING_TODOS";
export const SET_TODO = "SET_TODO";
export const START_LOADING_TODO = "START_LOADING_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const START_LOADING_STATUSES = "START_LOADING_STATUSES";
export const SET_STATUSES = "SET_STATUSES";
